### ISSUE TITLE
Failed to compile. issue

### ISSUE THREAD

**Issue by rwaneyvin** [bushblade/react-touch-drag-slider#5] opened 2022-11-16 02:35 UTC
Hello author,
I found this when using the slider, would you please help to advise what to do? thanks a lot!
./node_modules/react-touch-drag-slider/dist/lib.es.js 714:10
Module parse failed: Unexpected token (714:10)
You may need an appropriate loader to handle this file type

**Comment by bushblade** [comment] 2022-11-16 08:36
Hi there.
Can you give some more information please?
Ideally a reproduceable demonstration of how the issue occurs - a CodeSandbox or similar would be super useful.
What build system/framework are you using? Perhaps you're trying to use the ES module in a common JS way?

**Comment by bushblade** [comment] 2023-01-20 20:41
Closing due to lack of further information.

**Closed as completed by bushblade** 2023-01-20 20:41 UTC
